-- Add dual cutoff mode fields to Settings table
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "cutoffMode" TEXT NOT NULL DEFAULT 'per-shift';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "weeklyCutoffDay" INTEGER NOT NULL DEFAULT 5;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "weeklyCutoffHour" INTEGER NOT NULL DEFAULT 17;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "weeklyCutoffMinute" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "orderableDays" TEXT NOT NULL DEFAULT '1,2,3,4,5,6';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "maxWeeksAhead" INTEGER NOT NULL DEFAULT 1;
