-- AlterTable: Add NTP settings columns to Settings table
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ntpEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ntpServer" TEXT NOT NULL DEFAULT 'pool.ntp.org';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ntpTimezone" TEXT NOT NULL DEFAULT 'Asia/Jakarta';
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ntpSyncInterval" INTEGER NOT NULL DEFAULT 3600;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ntpLastSync" TIMESTAMP(3);
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "ntpOffset" INTEGER NOT NULL DEFAULT 0;
