-- AlterTable: Add Email SMTP settings columns to Settings table
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "emailEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpHost" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpPort" INTEGER NOT NULL DEFAULT 587;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpSecure" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpUser" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpPass" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "smtpFrom" TEXT;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "adminEmail" TEXT;
